import { NextApiRequest, NextApiResponse } from 'next';
import { supabaseAdmin } from '@/lib/database-server';
import { withErrorHandler } from '@/lib/api/middleware/error-handler';
import { authenticate, checkRole } from '@/lib/api/middleware/auth';
import { withRateLimit } from '@/lib/api/middleware/auth';
import { z } from 'zod';

// Validation schema
const inviteUserSchema = z.object({
  userId: z.string().uuid('Invalid user ID'),
});

// Rate limiting: 10 invitations per minute per admin
const rateLimitMiddleware = withRateLimit(10, 60 * 1000, (req) => {
  const token = req.headers.authorization?.replace('Bearer ', '');
  return token || req.socket.remoteAddress || 'unknown';
});

async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: {
        code: 'METHOD_NOT_ALLOWED',
        message: 'Only POST method is allowed',
        details: null
      },
      timestamp: new Date().toISOString()
    });
  }

  try {
    // Apply rate limiting
    rateLimitMiddleware(req);

    // Authenticate user
    const user = await authenticate(req);

    // Authorize admin access
    if (!checkRole(user.role, ['admin'])) {
      return res.status(403).json({
        success: false,
        error: {
          code: 'FORBIDDEN',
          message: 'Admin access required',
          details: null
        },
        timestamp: new Date().toISOString()
      });
    }
    
    // Validate request body
    const validatedData = inviteUserSchema.parse(req.body);
    const { userId } = validatedData;

    // Get the target user
    const { data: targetUser, error: targetUserError } = await supabaseAdmin
      .from('users')
      .select('*')
      .eq('id', userId)
      .single();

    if (targetUserError || !targetUser) {
      return res.status(404).json({
        success: false,
        error: {
          code: 'USER_NOT_FOUND',
          message: 'User not found',
          details: null
        },
        timestamp: new Date().toISOString()
      });
    }

    // Generate a password reset token for the user
    const { data: resetData, error: resetError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'recovery',
      email: targetUser.email,
      options: {
        redirectTo: `${process.env.NEXT_PUBLIC_SITE_URL}/auth/reset-password`
      }
    });

    if (resetError) {
      console.error('Error generating reset link:', resetError);
      return res.status(500).json({
        success: false,
        error: {
          code: 'LINK_GENERATION_FAILED',
          message: 'Failed to generate invitation link',
          details: resetError.message
        },
        timestamp: new Date().toISOString()
      });
    }

    // Log the invitation
    console.info(`User invitation generated by admin ${user.id}:`, {
      invitedUserId: targetUser.id,
      email: targetUser.email,
      role: targetUser.role
    });

    return res.status(200).json({
      success: true,
      data: {
        user: {
          id: targetUser.id,
          name: targetUser.name,
          email: targetUser.email,
          role: targetUser.role
        },
        invitationLink: resetData.properties?.action_link,
        instructions: 'Share this invitation link with the user. They will be able to set their password and log in.'
      },
      message: 'Invitation link generated successfully',
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('Invite user API error:', error);
    
    if (error instanceof z.ZodError) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Invalid input data',
          details: error.errors.map(err => ({
            field: err.path.join('.'),
            message: err.message
          }))
        },
        timestamp: new Date().toISOString()
      });
    }

    return res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'An unexpected error occurred while generating invitation',
        details: process.env.NODE_ENV === 'development' ? (error as Error).message : null
      },
      timestamp: new Date().toISOString()
    });
  }
}

export default withErrorHandler(handler);
