import { NextApiRequest, NextApiResponse } from 'next';

import { withErrorHandler } from '@/lib/api/middleware/error-handler';
import { withCMSSecurity } from '@/lib/security/cms-security';
import formidable from 'formidable';
import fs from 'fs';
import path from 'path';

export const config = {
  api: {
    bodyParser: false,
  },
};

async function handler(req: NextApiRequest, res: NextApiResponse, user: { id: string; email: string; securityLevel?: string }) {
  try {
    // Only allow POST for logo upload
    if (req.method !== 'POST') {
      return res.status(405).json({
        success: false,
        error: {
          code: 'METHOD_NOT_ALLOWED',
          message: 'Only POST method is allowed for logo upload',
          details: null
        },
        timestamp: new Date().toISOString()
      });
    }

    // Log admin logo upload action
    console.log(`Admin logo upload initiated`, {
      adminId: user.id,
      adminEmail: user.email,
      timestamp: new Date().toISOString()
    });

    // Configure formidable with enhanced security
    const form = formidable({
      uploadDir: path.join(process.cwd(), 'public'),
      keepExtensions: true,
      maxFileSize: 2 * 1024 * 1024, // 2MB
      filter: function (part: formidable.Part) {
        return Boolean(part.mimetype && part.mimetype.includes('image/'));
      },
      filename: function (name: string, ext: string) {
        return `logo-${Date.now()}${ext}`;
      }
    });

    const [, files] = await form.parse(req);

    const file = Array.isArray(files.logo) ? files.logo[0] : files.logo;

    if (!file) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'INVALID_REQUEST',
          message: 'No logo file provided',
          details: null
        },
        timestamp: new Date().toISOString()
      });
    }

    // Enhanced file type validation
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
    if (!allowedTypes.includes(file.mimetype || '')) {
      // Clean up uploaded file
      if (fs.existsSync(file.filepath)) {
        fs.unlinkSync(file.filepath);
      }
      return res.status(400).json({
        success: false,
        error: {
          code: 'INVALID_FILE_TYPE',
          message: 'Invalid file type. Only JPG, PNG, GIF, and WebP are allowed',
          details: null
        },
        timestamp: new Date().toISOString()
      });
    }

    // Use the actual filename generated by formidable
    const logoUrl = `/${file.newFilename}`;

    // Update site settings in JSON file
    const SETTINGS_FILE = path.join(process.cwd(), 'data', 'settings.json');
    let settings: any = {};
    
    try {
      const fileContent = await fs.promises.readFile(SETTINGS_FILE, 'utf-8');
      settings = JSON.parse(fileContent);
    } catch (error) {
      console.warn('Settings file not found or invalid, creating new object. Error:', error);
      // If file doesn't exist, we start with an empty object or defaults
      // We rely on the settings API to populate defaults if missing
    }

    // Update logo and metadata
    settings.site_logo = logoUrl;
    settings.updated_at = new Date().toISOString();
    settings.updated_by = user.id;

    // Write back to file
    await fs.promises.writeFile(SETTINGS_FILE, JSON.stringify(settings, null, 2));

    console.log(`Admin logo uploaded and settings.json updated`, {
      adminId: user.id,
      logoUrl,
      timestamp: new Date().toISOString()
    });

    return res.status(200).json({
      success: true,
      message: 'Logo uploaded successfully',
      data: { 
        logo_url: logoUrl,
        settings: settings,
        uploaded_by: user.id,
        file_info: {
          original_name: file.originalFilename,
          size: file.size,
          type: file.mimetype
        }
      },
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('Admin logo upload API error:', error);
    return res.status(500).json({
      success: false,
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'An unexpected error occurred while processing logo upload',
        details: process.env.NODE_ENV === 'development' ? (error as Error).message : null
      },
      timestamp: new Date().toISOString()
    });
  }
}

// Apply CMS security middleware and enhanced error handler
export default withErrorHandler(withCMSSecurity(handler, {
  requirePermission: 'upload:logo',
  auditAction: 'logo_uploaded'
}));
